USER_LIB_PATH=/Users/susie/dev/university/csc460/uvic-csc460/project1/common
LOCAL_CPP_SRCS=$(wildcard $(realpath ../common)/*.cpp)

BOARD_TAG    = mega
BOARD_SUB    = atmega2560
ARDUINO_PORT = ${REMOTE_PORT}
include ${ARDMK_DIR}/Arduino.mk
